### ISSUE TITLE
NOTICE: Use of undefined constant count - assumed 'count'

### ISSUE THREAD

**Issue by bbfriend** [cmb69/realblog_xh#17]
Hi!
I get 
NOTICE: Use of undefined constant count - assumed 'count'
 *****classes/ArticlesView.php 

    protected function renderCommentCount(Realblog_Article $article)
    {
     ･････
        $count = call_user_func(array($bridge, count), $commentsId);

to

        $count = call_user_func(array($bridge, 'count'), $commentsId);

**Comment by cmb69** [comment]
Thanks!
