### ISSUE TITLE
Headlines should not be hard-coded as <h4>

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#23]
Headlines (Titles) in Preview und Artikelansicht sind hardcodiert `<h4>`
Das bringt u.U. Probleme mit der Seitenstruktur (split-Variante).
Entweder config-Option (bevorzugt) wählbar: h1, h2, h3 ... abhängig vom Template.
oder als p class="..."

**Comment by cmb69** [comment]
> Entweder config-Option (bevorzugt) wählbar: h1, h2, h3 ... abhängig vom Template.

Ja, das erscheint sinnvoll (und ist leicht machbar). Wer individueller werden will, kann bei kommenden Versionen ja einfach die [View anpassen](https://github.com/cmb69/realblog_xh/blob/master/views/article.php#L14).

**Comment by frase-git** [comment]
> Wer individueller werden will, kann bei kommenden Versionen ja einfach die View anpassen.

Das habe ich bei meinen Tests schon gemacht.
Jetzt warte ich aber auf die neue Version. ;-)

**Comment by frase-git** [comment]
Habe nochmal etwas experimentiert.
Vielleicht besser jeden Teaser und jeden Artikel in `<article>` ... `</article>` setzen und dann immer mit `<h1>` beginnen. Damit ist die Struktur gewahrt und im Artikel stehen alle Überschriften zur Verfügung.

`realblog_buttons` sollte "oben" in der Artikelansicht weg. Es ist unlogisch, wenn man einen Artkel öffnet und als Erstes zurückgeschickt wird (zur Artikel-Übersicht). 
Diese Buttons sollten vielleicht auch in `<aside>`.

**Comment by cmb69** [comment]
> Besonders in der Artikelansicht sollte der Artikel-Titel oben als erstes stehen.
In "split" könnte man ja die erste Seitenüberschrift ausschalten ...
In 1.6.x ?
Hast du eine Idee?

Eigentlich nur nur #19.

**Comment by cmb69** [comment]
> Vielleicht besser jeden Teaser und jeden Artikel in <article> ... </article> setzen […]

Das wird bereits von #41 abgedeckt.

> realblog_buttons sollte "oben" in der Artikelansicht weg.

Diesbezüglich habe ich nun #50 geöffnet.
