### ISSUE TITLE
auto-archive und auto-publish

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#24]
Schwer zu beschreiben:
Ändere ich in der Konfiguration _nachträglich_ auto-archive und/oder auto-publish kommt es zu "komischen" Effekten.
Der Artikel (von heute)  erhält beim nächsten Speichern (auch ohne jegliche Änderung) immer Status 2, also archiviert.
Als Archivierungsdatum steht: 1970-01-01
Als Veröffentlichungsdatum ebenso: 1970-01-01

**Comment by cmb69** [comment]
Ja, das ist ein noch nicht behobener Bug, siehe #13.
