### ISSUE TITLE
Option to show teaser as lead above article

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#26]
In einigen Blogs wird der Teaser-Text 1:1 unterhalb der Artikel-Überschrift wiederholt.
Optisch leicht vom Fließtext abgehoben (semibold, Farbe o.Ä.).
Überschrift, Datum, (Autor), (Kommentaranzahl) und Vorspann bilden somit einen "Lead".
Das ist guter journalistischer Stil. ;-)
Könnte das hilfreich sein?
Evtl. um User ein bisschen zum Nachdenken anzuregen, was und wie sie da schreiben?

**Comment by cmb69** [comment]
Ja, das macht Sinn. Allerdings ist es wohl derzeit so, dass viele User den Teaser aus dem Artikel-Anfang kopieren (vielleicht auch etwas umgeschrieben). Daher müsste das per Konfigurationsoption gesteuert werden, sonst hätte man den gleichen Inhalt zweimal.

**Comment by frase-git** [comment]
> Daher müsste das per Konfigurationsoption gesteuert werden, sonst hätte man den gleichen Inhalt zweimal.

Konfigurationsoption: Soll der Teaser-Text als Vorspann vor dem Artikel wiederholt werden?
ja/nein
Wenn du das so meintest, einverstanden.
;-)

**Comment by cmb69** [comment]
> Wenn du das so meintest, einverstanden.

Ja, so meinte ich das.
