### ISSUE TITLE
Don't use <b> for stylistic purposes

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#27]
Im Code kommt an einigen Stellen `<b>` vor.
Zum Beispiel in MainController.php ab Zeile 40 ... und an anderen Stellen.
Wäre es nicht besser solche Design-Versuche per css-Klasse zu lösen?

**Comment by cmb69** [comment]
> um Beispiel in MainController.php ab Zeile 40

[MainController::renderSearchResults()](https://github.com/cmb69/realblog_xh/blob/master/classes/MainController.php#L40-L52) ist insgesamt grausig:
`gefundene Artikel: 23`

> Wäre es nicht besser solche Design-Versuche per css-Klasse zu lösen?

Ja, solche Altlasten müssen raus.

**Comment by cmb69** [comment]
Ich habe mal nach `<b>` gesucht, und konnte es nur in der Suchergebnisanzeige und in der [Archiv-View](https://github.com/cmb69/realblog_xh/blob/master/views/archive.php) finden. Die Suchanzeige habe ich gerade zu einer [View](https://github.com/cmb69/realblog_xh/blob/master/views/search-results.php) refaktoriert.

@frase-git Mach doch bitte mal einen konkreten Vorschlag, wie diese beiden Views bezüglich der Gestaltbarkeit verbessert werden könnten.

**Comment by frase-git** [comment]
http://www.fhseidel.de/cmsxh/split-196-realblog/

Ist immer noch nicht fertig - aber schon weiter.
Die Suche im Blog habe ich stark verändert.
functions.php + Presentation.php

Das Aufklappen hat dein "altest" Javascript + eine Abfrage, ob jQueri da ist.
Wenn ja, dann smooth ...

**Comment by cmb69** [comment]
> Die Suche im Blog habe ich stark verändert.
functions.php + Presentation.php

[Habe ich auch schon](https://github.com/cmb69/realblog_xh/commit/75483d39f7fadf9765b8139e8037b740ab30ed3e). Da gibt es mittlerweile nichts mehr zum Ausklappen, also auch kein JS; es sieht nun einfach so aus:

![realblog-search](https://cloud.githubusercontent.com/assets/2306138/22549693/deccef28-e94c-11e6-8c3e-82651eaabc6e.jpg)

Es wird nun immer im Titel und im Body gesucht; die vorherige Variante erscheint mir Overkill.

**Comment by frase-git** [comment]
Ja ja, ich weiß.
Ich habe aber noch die alte Blog-Version verwendet.
Das ist sowieso alles ein bisschen ungünstig, da die neue Version noch Bugs hat.
Deine neue Suche hat den Nachteil, dass sie genau so aussieht, wie die site-weite.
Das mit dem Ausklappen fand ich gar nicht so schlecht. Es gibt wohl aber keine Such-Optionen mehr?
Dann wäre es überflüssig.
Egal.
Vielleicht ist die Ergebnisanzeige im `fieldset` mit `legend` eine Inspiration.
Das muss sich irgendwie vom Rest abheben.

Mal abgesehen davon, ist die obige Adresse mehr ein Test für split mit 1.6.9 (inkl. aller Fixes)
MIt dem Blog habe ich nur experimentiert - bis die neue Version da ist.
Dann wollte ich Ernst machen.

**Comment by cmb69** [comment]
> Das ist sowieso alles ein bisschen ungünstig, da die neue Version noch Bugs hat.

Ja, gewiß. Aber 3.0beta5 hatte auch [eine Reihe Bugs](https://github.com/cmb69/realblog_xh/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20label%3Abug%20milestone%3A3.0beta6%20).

> Vielleicht ist die Ergebnisanzeige im fieldset mit legend eine Inspiration.

`<fieldset>` ist [für Formulare gedacht](https://www.w3.org/TR/html/sec-forms.html#the-fieldset-element):
> The fieldset element represents a set of form controls optionally grouped under a common name.

Kein Formular – kein Fieldset. Aber man kann es ja auch anders besser gestalten,

> MIt dem Blog habe ich nur experimentiert - bis die neue Version da ist.
Dann wollte ich Ernst machen.

Denk dran, dass als nächstes 3.0*beta*6 kommt. Da kann sich immer noch viel ändern.

**Comment by frase-git** [comment]
> [cmb69] Habe ich auch schon. Da gibt es mittlerweile nichts mehr zum Ausklappen, also auch kein JS; es sieht nun einfach so aus:

Irgendwie schnalle ich das nicht. Wo finde ich denn die SearchFormView.php ?
Ist in keinem Download enthalten.

**Comment by cmb69** [comment]
> Irgendwie schnalle ich das nicht. Wo finde ich denn die SearchFormView.php ?

Ich glaube, die Datei gab es nie. Jedenfalls ist das Relevante jetzt [search-form.php](https://github.com/cmb69/realblog_xh/blob/master/views/search-form.php). Schön überschau- und anpassbar.

**Comment by frase-git** [comment]
Das ist ja das Verwirrende. Wenn ich deinen Link von oben anklicke, komme ich zu genau dieser Datei: SearchFormView.php

**Comment by cmb69** [comment]
> Das ist ja das Verwirrende. Wenn ich deinen Link von oben anklicke, komme ich zu genau dieser Datei: SearchFormView.php

Ah, stimmt! Die Datei gab es gerade mal zwei Tage; dann wurde sie [Opfer eines Refactorings](https://github.com/cmb69/realblog_xh/commit/672d25a1c#diff-e61395e97f445bbf62a187c049c1b79f).
