### ISSUE TITLE
Haupt-Blogseite ist aktiver Menüpunkt

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#28]
Lese ich einen Artikel, ist es die gleiche Seite, wie die Blog-Hauptseite.
Im Menü ist der Menüpunkt also nicht anklickbar (um zurückzukommen).
Logisch: Dazu gibt es ja den Button "zur Artikel-Übersicht".
Bin ich ein Troll, wenn ich das nicht so schön finde?

**Comment by cmb69** [comment]
> Bin ich ein Troll, wenn ich das nicht so schön finde?

Nein, bist Du nicht, aber das liegt nicht in der Hand des Plugins (andere Plugins haben das gleiche Problem, wie z.B. Forum_XH und Galerien mit Paginierung). Die sauberste Lösung wäre wohl etwas wie #19, wobei dann der Blog im Hauptmenü gar nicht auftauchen würde (muss ich mal drüber nachdenken).

**Comment by frase-git** [comment]
> (muss ich mal drüber nachdenken)

Bitte nicht zu lange und nicht zu viel. Soll 'ne Anregung sein - keine Forderung.
Und unter "Probleme" (issues) gehört es eigentlich auch nicht.

**Comment by cmb69** [comment]
> Und unter "Probleme" (issues) gehört es eigentlich auch nicht.

Zumindest bei Github schon. Selbst Supportanfragen sind hier okay.

**Comment by cmb69** [comment]
Ein Fix für diese Sache wäre nur mit hässlicher Trickserei (entweder das globale $s verändern, oder per JS das Menü ändern) möglich, so dass ich dieses Ticket mal als WONTFIX schließe. Es bleibt ja noch #19.
