### ISSUE TITLE
Category selection

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#29]
Wäre es möglich, falls es schon Artikel mit zugeordneter Kategorie gibt, diese als DropDown-Auswahl anzubieten?
Kategorien -> input -> realblog_categories
Eintippen ist fehlerträchtig.

Oder gleich Kategorien vorher anlegen und dann als Auswahl?

**Comment by cmb69** [comment]
> Wäre es möglich, falls es schon Artikel mit zugeordneter Kategorie gibt, diese als DropDown-Auswahl anzubieten?

Das ist sinnvoll und möglich.

> Oder gleich Kategorien vorher anlegen und dann als Auswahl?

Das ist längerfristig sinnvoll. Dafür sollte die DB aber normalisiert werden (sprich, die Kategorien wandern in eine eigene Tabelle), und man bräuchte halt eine eigene Kategorieverwaltung.

**Comment by cmb69** [comment]
> > Wäre es möglich, falls es schon Artikel mit zugeordneter Kategorie gibt, diese als DropDown-Auswahl anzubieten?
>
> Das ist sinnvoll und möglich.

Zur Klarstellung: ein `<select>` ist nicht möglich (da man dann ja keine neuen Kategorien anlegen könnte), aber ein `<input list>` sollte vergleichbar komfortabel sein (insofern vom Browser unterstützt). Das würde ich zeitnah umsetzen.

**Comment by frase-git** [comment]
Hm.
Safari und Android-Browser unterstützen `input list` überhaupt nicht.
Das wäre mir zu gefährlich.
Vielleicht:
`<select>` für vorhandene PLUS
Eingabefeld: Kategorie neu anlegen

**Comment by cmb69** [comment]
> Safari und Android-Browser unterstützen input list überhaupt nicht.
Das wäre mir zu gefährlich.

Na ja, es wäre halt ein progressive enhancement. Wenn's der Browser nicht unterstüzt, dann hat der Anwender halt Pech – es wird aber auch nicht schlechter als bisher.

Ich habe gerade PR #39 eingestellt, dass eine datalist implementiert. Ich bin davon nicht wirklich überzeugt, aber es könnte eine Übergangslösung sein (eine richtige Kategorieverwaltung inklusive Normalisierung der DB will ich eigentlich für 3.0beta6 nicht mehr machen). Du kannst es ja [mal ausprobieren](https://github.com/cmb69/realblog_xh/archive/category-selection.zip).

> Vielleicht:
`<select>` für vorhandene PLUS
Eingabefeld: Kategorie neu anlegen

Ist mir eigentlich zu halbgar – was ist mit Umbenennen und Löschen?

**Comment by frase-git** [comment]
> Du kannst es ja mal ausprobieren.

Das werde ich tun. Später :-(

> Ist mir eigentlich zu halbgar – was ist mit Umbenennen und Löschen?

Es ist spät, ich blicke kaum noch durch.
Ich hatte mir das so vorgestellt:
Beim Bearbeiten oder Anlegen eines Artikels gibt es ein Eingabefeld für eine Kategorie.
Will man eine wählen die es schon gibt, sollte man sie irgendwo sehen können, draufklicken - und dieser Kategorietitel wird in das Eingabefeld übertragen. Das sichert nur ab, dass man sich nicht vertippt und aus Versehen eine neue anlegt, statt den Artikel einer vorhandenen hinzuzufügen.
Das ist keine Kategorieverwaltung, sondern nur ein bisschen Komfort.
Umbenennen und Löschen von Kategorien geht damit natürlich nicht. Dazu braucht es eine echte Kategorieverwaltung.
Irgendwann wird es sowieso dazu kommen müssen. Die Leute werden keine Ruhe geben.
Was ist eigentlich mit Svasti los? miniblog hatte schon ziemlich viele gute Ansätze. Nur das Userinterface ist viel zu kompliziert.

**Comment by cmb69** [comment]
> Irgendwann wird es sowieso dazu kommen müssen. Die Leute werden keine Ruhe geben.

Ja, ich weiß. Aber jetzt nur eine mäßige Unterstützung einzuführen, könnte zwei Nachteile haben:
* ich investiere jetzt nicht wenig Zeit in ein Feature, dass später komplett ersetzt wird
* die Leute werden erst recht keine Ruhe geben

Letztlich finde ich, dass der Kategorie-Support von 3.0beta5 schon mal deutlich verbessert ist, und werde da für 3.0beta6 nichts mehr unternehmen – sonst dauert es vielleicht noch mal Wochen oder gar Monate.

> Was ist eigentlich mit Svasti los?

Frank hat wohl derzeit zu viel mit dem "wirklichen Leben" zu tun, und leider sehr wenig Zeit für Open-Source. Das ändert sich aber hoffentlich bald wieder. :)

**Comment by frase-git** [comment]
> Letztlich finde ich, dass der Kategorie-Support von 3.0beta5 schon mal deutlich verbessert ist, und werde da für 3.0beta6 nichts mehr unternehmen ...
Einverstanden- Alläs subär!

**Comment by cmb69** [comment]
> Einverstanden- Alläs subär!

Primma! Dann, wenn Du magst, ab zur [3.0beta6](https://cmsimpleforum.com/viewtopic.php?f=16&t=7918&p=57539#p57539) und v.a. auf Fehler testen.
