### ISSUE TITLE
Improve search-form.php

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#37]
Betrifft ab jetzt nur noch `master`. (noch nicht online)

Ungünstig:
Alles in `<p> ... </p>` zu packen.
Theoretisch braucht es gar kein Block-Element. Man könnte sogar das Formular ansprechen und stylen (realblog_search_form).
Besser:
Um alles herum (inkl. Formular-Tag) ein `div` mit Klasse. `<p>`und `</p>` entfernen.
(Oder ein `<aside>`, nur da wollen die Struktur-Fetischisten wieder ein `h1` dazu. Also besser nicht.)
Den DIV kann man frei gestalten und alle Elemente darin eindeutig ansprechen. Eigentlich müsste der submit-Button auch eine Klasse oder ID haben, geht aber so.

Was ich wirklich noch wichtig finde, ist die submit-Button-Beschriftung. Kommt nicht aus dem Plugin. Ist identisch mit der XH-Suche (Verwechslungsgefahr).
Besser wäre hier eine eigene Sprachvariable, z.B. "Suche im Blog".

Ob `size="15"` nötig ist?

Nebenfrage:
Ich habe die styles.css im Pluginordner umbenannt und per Template ein eigens eingebunden.
Die plugins.css wird aber nicht aktualisiert. Denkfehler?

Result-Anzeige folgt später.

**Comment by cmb69** [comment]
> Um alles herum (inkl. Formular-Tag) ein div mit Klasse. `<p>` und `</p>` entfernen.

Das `<p>` kann wirklich weg, aber warum noch ein `<div>` drum herum? Ich kann da keinen Vorteil gegenüber dem direkten gestalten des `<form>` sehen (bin halt aber auch kein Designer).

> Eigentlich müsste der submit-Button auch eine Klasse oder ID haben, geht aber so.

Ich denke, dass ein `realblog_search_form button` Selektor vielleicht die bessere Variante ist; sprich, das `<input type=submit>` wird zu `<button>`.

> Was ich wirklich noch wichtig finde, ist die submit-Button-Beschriftung. Kommt nicht aus dem Plugin. 

Das ist schon eine [Plugin-Sprachvariable](https://github.com/cmb69/realblog_xh/blob/master/languages/de.php#L61). Vielleicht eine andere Default-Belegung? Hm, "Suchbegriff eingeben" finde ich eigentlich gut, weil damit klar ist, dass es um einen Begriff geht, und nicht mehrere (wie bei der CMSimple_XH Suche).

> Ob size="15" nötig ist?

Nein. Und `maxlength` hat auch keinen Sinn.

> Ich habe die styles.css im Pluginordner umbenannt und per Template ein eigens eingebunden.
Die plugins.css wird aber nicht aktualisiert. Denkfehler?

Beim Erstellen von plugins.css werden wirklich [nur plugins/*/css/stylesheet.css berücksichtigt](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.6.9/cmsimple/functions.php#L2015-L2028). Verlinkung von anderen Stylesheets per Template oder `@import` werden ignoriert (das wäre zu aufwendig in der Umsetzung).

**Comment by frase-git** [comment]
> aber warum noch ein `<div>` drum herum? Ich kann da keinen Vorteil gegenüber dem direkten gestalten des `<form>` sehen

Gut. Dachte ich mir. War mir aber nicht ganz sicher. DIV braucht's also nicht.
Habe nochmal nachgelesen.  `<form>` ist ein echtes Block-Element.

> Ich denke, dass ein realblog_search_form button Selektor vielleicht die bessere Variante ist; sprich, das `<input type=submit>` wird zu `<button>`.

Okay.

> Das ist schon eine Plugin-Sprachvariable.

Sorry, da habe ich mich geirrt. Die Belegung sollte eben nur klar machen, dass nur in den Blog-Beiträgen gesucht wird. Das kann so aber jeder selbst entscheiden.

plugins.css:
Das hat sich geklärt. Die plugins.css hatte sich nicht aktualisiert. Jetzt klappt aber alles, wie es soll.
Ich teste ja nur. Nicht so wichtig.

**Comment by frase-git** [comment]
Mal noch 'ne ganz andere Frage:
Es scheint für den Code für XH und Plugins keine richtige Regel, was Einrückung ja/nein, Tabs oder Leerzeichen usw. zu geben.
Wenn ich mir so manchen Seiten-Quelltext ansehe ...
Ich bin mittlerweile dazu übergegangen, bei html nicht mehr einzurücken. Und schon gar nicht mit Leerzeichen. Das ist zwar ein minimaler Effekt, macht aber doch was in der Menge aus.
In den php-Codes sehe ich auch oft noch `\n`, was eigentlich bei utf-8 auch nicht nötig ist.
Es geht doch auch so. Beispiel:
```
<?php echo ('
xxx
'); ?>
```
Ergibt eine Zeile mit xxx am Anfang ohne Einrückung.
Oft sehe ich in Quelltexten auch zum Beispiel Skript-Aufrufe, CSS-Aufrufe und anderes - alles hintereinander in einer Zeile. Nicht schön - aus Sicht eines Nicht-Programmierers.

**Comment by cmb69** [comment]
> Habe nochmal nachgelesen. `<form>` ist ein echtes Block-Element.

Soweit ich weiß kennt HTML5 keine Blockelemente mehr. Scheint nun irgendwie komplizierter zu sein.

> Es scheint für den Code für XH und Plugins keine richtige Regel, was Einrückung ja/nein, Tabs oder Leerzeichen usw. zu geben.

Für das erzeugte HTML gibt es bezüglich Whitespaces tatsächlich keinerlei Regel. Beim Original-CMSimple gab es kaum Whitespace. In den Anfängen von CMSimple_XH wurden dann viele Zeilenumbrüche ergänzt. Ich habe das früher bei meinen Plugins auch gemacht, aber das wurde mir zu aufwendig, und das Ergebnis war trotzdem äußerst bescheiden. Und vor allem spielt das heutzutage im Zweifel keine Rolle mehr, da die Developertools der Browser die Elementstruktur sowieso sauber und übersichtlich darstellen – ich habe selten Grund mir das HTML anzuschauen.

Ein netter Nebeneffekt von Views, auf die ich mehr und mehr umstelle, ist allerdings: what you see is what you get (na ja, weitgehend zumindest). Ich verwende Einrückungen, um die Views besser lesen zu können (hebt sich nett vom eigentlichen PHP ab). Und ich bevorzuge mittlerweile Spaces für Einrückungen (keine Tabs mehr), weil es mit unterschiedlichen Tabulatorweiten immer wieder Probleme gibt. Eigentlich halte ich das auch bezüglich der Datenmenge für kein echtes Problem – eigentlich sollte der Austausch komprimiert erfolgen, und da nimmt sich's nicht mehr viel. Ich könnte das natürlich im Build-Script wohl auch leicht ändern (so wie die `<?=` in `<?php echo ` konvertiert werden).
