### ISSUE TITLE
Improve search result presentation

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#38]
So könnte es aussehen:
```
<!-- realblog search results / as table -->
<div class="searchResults">
<div class="sRrow">
<div class="sRtd"><?=$this->text('search_searched_for')?></div>
<div class="sRtd"><?=$this->words?></div>
</div>
<div class="sRrow">
<div class="sRtd"><?=$this->text('search_result')?></div>
<div class="sRtd"><?=$this->count?></div>
</div>
</div>
<div class="realblog_button"><a href="<?=$this->url?>"><?=$this->text($this->key)?></a></div>
```
Dazu CSS:
```
div.searchResults {
margin: 1em 0;
display: table;
border-collapse: collapse;
}
div.searchResults .sRrow {
display: table-row;
}
div.searchResults .sRtd {
display: table-cell;
padding: .25em .5em;
border: 1px dotted #999;
}
```
Das sollte allgemein passen.
Individuelle Gestaltung auf der Testseite folgt (morgen?).

**Comment by cmb69** [comment]
Danke! :)

Ich frage mich halt, ob ein vollständiger Satz nicht angebracher wäre, vielleicht in der Sprachdatei
````
$plugin_tx['realblog']['search_results']="\"%s\" wurde in %d Artikeln gefunden.";
````

Dann könnte der Anwender bei Bedarf selbst noch `<span>`s oder was auch immer ergänzen, und nach Lust und Laune gestalten.

Die Implementierung ist nicht super-trivial (Singular/Plural), aber bevor nun eine neue HTML-Struktur mit neuen CSS-Klassen eingeführt wird, würde ich es bevorzugen, gleich (also für 3.0beta6) umzustellen.

**Comment by frase-git** [comment]
Okay. Obwohl es ja nur die eine Datei wäre.
Aber wenn schon, dann gleich:

`$plugin_tx['realblog']['search_results']="<span>\"%s\"</span> wurde in <span>%d</span> Artikeln gefunden.";`

Da sind dann die "spans" schon drin. Wer es stylen will, kann - wer nicht, bei dem passiert gar nichts.
Wenn das der User selbst in die Sprach-Konfig einfügen soll, gibts Chaos. Ich bin mir nicht sicher, ob ich die "spans" hier an der richtigen Stelle eingefügt habe.

Der Satz sollte auch eine eindeutige Klasse haben. Nicht nur wieder einfach irgendwo ein `<p>`.
Zusätzlich fände ich auch noch eine Überschrift gut.

`$plugin_tx['realblog']['search_results']="Suchergebnis";`

**Comment by cmb69** [comment]
> Aber wenn schon, dann gleich:
>
> `$plugin_tx['realblog']['search_results']="<span>\"%s\"</span> wurde in <span>%d</span> Artikeln gefunden.";`

Okay, warum nicht. Allerdings würde ich den spans dann noch Klassen mitgeben – die Reihenfolge könnte in manchen Sprachen anders sein, und auch im Deutschen könnte man ja vielleicht umstellen wollen ("99 Treffer für den Begriff "Suchbegriff").

> Ich bin mir nicht sicher, ob ich die "spans" hier an der richtigen Stelle eingefügt habe.

Ja, ist nicht klar ob die spans innerhalb oder außerhalb der Anführungszeichen platziert werden sollen. Daher hatte ich es bei meiner ersten Variante auch komplett dem User überlassen. Vermutlich ist es das beste, einfach eine Variante zu wählen (Dein Vorschlag erscheint passend); der Webmaster kann das dann immer noch ändern. (Und ja, es sollten die richtigen Anführungszeichen verwendet werden; und nein, diese sollten nicht nur per CSS injiziert werden.)

> Der Satz sollte auch eine eindeutige Klasse haben.

Ja!

> Zusätzlich fände ich auch noch eine Überschrift gut.

Wirklich? Die könnte auch (angepasst) in der Sprachzeichenkette stehen.

Andererseits: wenn ich an die Views denke, dann wäre es vielleicht doch besser die einzelnen Variablen zur Verfügung zu stellen, und nicht gleich die gesamte lokalisierte Zeichenkette. Vielleicht geht auch beides? Da muss ich noch mal drüber schlafen.

**Comment by cmb69** [comment]
> Okay. Obwohl es ja nur die eine Datei wäre.

Vielleicht ein interessanter Gedanke (vielleicht auch nur ein Spinnerei): man könnte alternative Views ausliefern, evtl. sogar einfach per Konfigurationsoption umschaltbar – Stichwort "Theme". Für die Stylesheets hätte ich allerdings (noch?) keine Lösung parat.

**Comment by frase-git** [comment]
Eine wirklich gute Idee.
In Anbetracht der Tatsache, dass du ja gar nicht weißt, wie du deine Zeit verbringen sollst ...
;-)
Das übergeben wir mal der nächsten Generation - den Praktikanten ...

**Comment by cmb69** [comment]
@frase-git Schau Dir bitte mal den [search-results Branch](https://github.com/cmb69/realblog_xh/archive/search-results.zip) an. Ich denke, das kann vorerst so bleiben. Mittelfristig würde ich dann aber schon HTML5 Strukturelemente verwenden, aber das dann für den gesamten Blog, siehe issue #41.

**Comment by frase-git** [comment]
> Schau Dir bitte mal den search-results Branch an.

Sorry. Entweder ich bin völlig ahnungslos, oder der Link stimmt nicht.
Wonach soll ich denn schauen?
Das ist genau die alte Version.
Suchergebnisse:
Alles beim Alten.
"Alle Artikel anzeigen »" ist wieder fett.
???

Was ich aber noch habe (unabhängig von dieser Version):
Beim Bearbeiten eines ARtikels meldet der Debug-Modus:

> NOTICE: Use of undefined constant TINYMCE4_VARIANT - assumed 'TINYMCE4_VARIANT'
D:\xampp-5-6-11\htdocs\sites\_cmsxh\split-196-realblog\plugins\tinymce4\init.php:98
NOTICE: Use of undefined constant TINYMCE4_VARIANT - assumed 'TINYMCE4_VARIANT'
D:\xampp-5-6-11\htdocs\sites\_cmsxh\split-196-realblog\plugins\tinymce4\init.php:219

**Comment by cmb69** [comment]
> Sorry. Entweder ich bin völlig ahnungslos, oder der Link stimmt nicht.

Der Link verweist auf ein komplettes Realblog_XH Plugin mit den entsprechenden Änderungen (hab's gerade noch mal überprüft). Aber eigentlich reicht es, wenn Du Dir die [geänderte search-results.php](https://github.com/cmb69/realblog_xh/pull/42/files#diff-7cb3a81d699cd485b4c1fe5c38b12761) anschaust. Aussehen sollte es etwa wie folgt:

![realblog-search](https://cloud.githubusercontent.com/assets/2306138/22593596/9e5db868-ea1f-11e6-8b00-1125c9e98e03.jpg)

> Beim Bearbeiten eines ARtikels meldet der Debug-Modus:

Hm, das ist garstig, vor allem weil es inzwischen so aussieht, als ob dieses ["Feature" ab PHP 7.2.0 deprecated wird](https://cmsimpleforum.com/viewtopic.php?f=29&t=12398#p57421). Das hat aber nichts mit Realblog, sondern mit TinyMCE 4 zu tun. @manu37 Kannst Du [das](https://sourceforge.net/p/tinymce4cmsimplexh/code/HEAD/tree/trunk/tinymce4/init.php#l98) und [das](https://sourceforge.net/p/tinymce4cmsimplexh/code/HEAD/tree/trunk/tinymce4/init.php#l220) bei Gelegenheit bitte beheben?

**Comment by manu37** [comment]
Helft mir doch schnell auf die Sprünge. TINYMCE_VARIANT wird in plugins/tinymce4/index.php definiert. Ist dies ein plugins Reihenfolge Problem?

**Comment by frase-git** [comment]
@manu37 
Da halte ich mich lieber raus ;-)

@cmb69 
Ich hatte vorhin tatsächlich eine alte Version runtergeladen (aus dem Link).
Jetzt, mit erneutem Download, funktioniert die Suche super!
Alles gut stylebar. Schön Formuliert (Plural...).
Gute Arbeit.
Danke.

**Comment by cmb69** [comment]
> Ist dies ein plugins Reihenfolge Problem?

Auf die Schnelle würde ich sagen, ja. Der Realblog initialisiert den Editor über index.php, wobei init.php inkludiert wird, und erst später wird index.php von TinyMCE 4 geladen. Wenn Du die Definition nach classes/required_classes.php verschiebst, sollte das Problem gelöst sein.

> Alles gut stylebar. Schön Formuliert (Plural...).

Prima. Dann werde ich PR #42 mergen.

**Comment by manu37** [comment]
Also Frank, der einstweilige patch sieht folgendermassen aus:
in plugins/tinymce4/ :
verschiebe aus index.php die "define" statements line 43-46 nach
classes/required_classes.php in line 26.
Dann sollten die Warnings aufhören.
Das nächste was ich mache, ist der Umzug von SF nach Github. 
...wenn ich Zeit finde ...
Gruss
manu

**Comment by frase-git** [comment]
@manu37 
Danke. Funktioniert (für mich) perfekt.
Und wieder superschnell! ;-)

BTW: Die Fehlermeldung hat die Funktionalität (scheinbar) nicht beeinträchtigt.

**Comment by manu37** [comment]
@frase-git 
ist ja auch nur eine (selbstheilende) Warnung..

**Comment by cmb69** [comment]
> ist ja auch nur eine (selbstheilende) Warnung..

Dachte ich auch zuerst, aber in diesem Fall wurde nie die CDN-Version gezogen, obwohl das der Default ist, da `'TINYMCE4_VARIANT' != 'CDN'`. Daher hoffe ich auch sehr, dass die Deprecation dieses "Feature" akzeptiert wird. Dann (also ab PHP 8) wäre auch die leidige `XH_ADM` Inkompatibilität mit CMSimple vom Tisch.

**Comment by manu37** [comment]
Da hast Du recht, Realblog oder ein anderes plugin, das den editor benützt und dann noch die CDN Variante. Werde das nächstens ausbügeln.
