### ISSUE TITLE
Back to overview after search

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#40]
Wenn ich im Blog suche und einen Treffer habe.
Ich klicke auf "Artikel lesen".
Ich lese den Artikel und unten steht "zur Artikel-Übersicht".
Der Link führt aber zur Suchseite mit den Suchergebnissen.
... /?Realblog&realblog_search=und

**Comment by cmb69** [comment]
Das ist ein Bug. Danke!

**Comment by cmb69** [comment]
Hm, wie soll das gelöst werden? Ein "zurück zu den Suchergebnissen" kann ja schon sinnvoll sein. Manchmal will man aber auch direkt zurück zur Gesamtübersicht. Also zwei Buttons (Links)?

**Comment by frase-git** [comment]
Na ja, wenn man mehrere Treffer hatte und nicht den richtigen angeklickt hat, will man vielleicht wirklich zurück zu den Suchergebnissen ...
Mir scheint das Eine wie das Andere ungünstig.
Also wirklich zwei Buttons? Vielleicht direkt untereinander/nebeneinander?
Nur, wie sieht das aus?

**Comment by cmb69** [comment]
> Also wirklich zwei Buttons? Vielleicht direkt untereinander/nebeneinander?

Na ja, im Adminmodus sind da sowieso schon [zwei bis drei Buttons](https://github.com/cmb69/realblog_xh/blob/master/views/article.php#L6-L11) (Artikel und Kommentare bearbeiten). Das dürfte auch im "Besucher-Modus" okay sein.

**Comment by frase-git** [comment]
Machen.
;-)

**Comment by cmb69** [comment]
Okay so?

**Comment by frase-git** [comment]
> Okay so?

Yes, Sir.
Abgesehen davon, dass nur oben die beiden Buttons bei mir erscheinen.
Ich muss später nochmal schauen, ob das an mir liegt.

**Comment by cmb69** [comment]
> Abgesehen davon, dass nur oben die beiden Buttons bei mir erscheinen.
Ich muss später nochmal schauen, ob das an mir liegt.

Nein, ist mein Fehler. Werde ich gleich nachbessern.

**Comment by cmb69** [comment]
> Werde ich gleich nachbessern.

Erledigt.

**Comment by frase-git** [comment]
Danke.
Wo finde ich denn die neueste Änderung?
