### ISSUE TITLE
Time of RSS <pubDate> is always 00:00:00

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#45]
Alle meine Artikel haben das richtige Datum in der RSS-Ansicht.
Nur die Uhrzeit ist immer " 00:00".

**Comment by cmb69** [comment]
Der Realblog arbeitet eigentlich nur mit dem Datum – die Uhrzeit wird ignoriert. Das [RSS `<pubDate>` Element](http://cyber.harvard.edu/rss/rss.html#ltpubdategtSubelementOfLtitemgt) erwartet aber ein Datum im [RFC 822 Format](https://tools.ietf.org/html/rfc822#section-5), beim dem die Uhrzeit verpflichtend ist. Und wenn eben ein Datum keine Uhrzeitinfo mitführt, dann wird diese halt als 00:00 angezeigt.

Ich sehe zwei alternative Lösungsmöglichkeiten:
1. im Artikelformular auch die Uhrzeit verwalten
1. im RSS-Feed einfach eine bestimmte Uhrzeit verwenden (evtl. konfigurierbar?)

(1) ist natürlich sauberer, bedeutet aber auch wieder Mehraufwand, nicht nur, um das zu programmieren, sondern auch wenn das Datum manuell geändert wird. Außerdem dürfte es Probleme geben, wenn `<input type=time>` bzw. `<input type=datetime-local>` nicht unterstützt wird – bin nicht sicher, ob der alternative DatePicker auch Zeiten unterstützt.

Wirklich wichtig finde ich die Uhrzeit allerdings nur, wenn tatsächlich mehrere Artikel am Tag veröffentlicht werden.

Was meinst Du?

**Comment by frase-git** [comment]
Verstehe.
In meinem Fall ist das alles egal. Fragen werden sicher von Anderen kommen.
(2) finde ich nicht gut.
Geht es nicht, bei jedem Speichern eines Artikels (anlegen/ändern) an das Datum die aktuelle Uhrzeit anzuhängen? Die muss ja nirgends sonst angezeigt oder gändert werden. Nur im Feed.
Archivierung und Veröffentlichung würde ich immer um 00:00 machen. Einfach irgendwo festlegen.

Apropos: Archivierung und Veröffentlichung
Artikel heute angelegt hat Datum für beides: 2038-01-19
Aber das ist wohl schon irgendwo in Arbeit ...?
Und dass Standard auf "Nicht veröffentlicht" steht, finde ich auch nicht so günstig. Ich musste wieder suchen, warum der Artikel nicht erscheint ;-)

**Comment by cmb69** [comment]
> Geht es nicht, bei jedem Speichern eines Artikels (anlegen/ändern) an das Datum die aktuelle Uhrzeit anzuhängen?

Hm, ist, glaube ich, ein bisschen Frickelei, sollte aber machbar sein, falls beim Speichern das Datum geändert wurde (und nur dann).

> Die muss ja nirgends sonst angezeigt oder gändert werden. Nur im Feed.
Archivierung und Veröffentlichung würde ich immer um 00:00 machen. Einfach irgendwo festlegen.

Okay, das passt.

> Artikel heute angelegt hat Datum für beides: 2038-01-19

Das war [Absicht](https://github.com/cmb69/realblog_xh/issues/13), weil sonst bei späterer Aktivierung von auto-publishing/-archiving plötzlich unveröffentlichte Artikel veröffentlich bzw. veröffentlichte archiviert werden. Okay, wenn auto-publishing aktiv ist, dann könnte natürlich auch das aktuelle Datum eingetragen werden, aber siehe weiter unten.

> Und dass Standard auf "Nicht veröffentlicht" steht, finde ich auch nicht so günstig. Ich musste wieder suchen, warum der Artikel nicht erscheint ;-)

Super finde ich das auch nicht, aber andernfalls wird der Artikel nach dem ersten Speichern veröffentlicht (wie auch wenn das Veröffentlichungsdatum auf das aktuelle Datum gesetzt wird), es sei denn man schaltet manuell auf nicht veröffentlicht (bzw. setzt bei auto-publishing das Veröffentlichungsdatum in die Zukunft).

Hier stellt sich die Frage, wie der Workflow normalerweise aussieht. Bei CMSimple-Seiten wird sofort veröffentlicht – da sollte der Realblog wohl mitziehen. Wäre für User, die den Realblog schon lange nutzen u.U. aber eine ganz schöne Umstellung. Vielleicht eine Konfigurationsoption?

**Comment by frase-git** [comment]
> Hm, ist, glaube ich, ein bisschen Frickelei, sollte aber machbar sein, falls beim Speichern das Datum geändert wurde (und nur dann).
Na dann, frickle mal ;-)

> Hier stellt sich die Frage, wie der Workflow normalerweise aussieht. Bei CMSimple-Seiten wird sofort veröffentlicht – da sollte der Realblog wohl mitziehen. Wäre für User, die den Realblog schon lange nutzen u.U. aber eine ganz schöne Umstellung. Vielleicht eine Konfigurationsoption?

Da muss ich nachdenken. Das wird alles zu kompliziert und aufwändig.
Ich neige im Moment eher zum "normalen" Workflow.

**Comment by cmb69** [comment]
> Da muss ich nachdenken. Das wird alles zu kompliziert und aufwändig.

Lass Dir ruhig Zeit, und poste dann Deine Entscheidung bitte bei Issue #48. :)

**Comment by frase-git** [comment]
Funktioniert bei Änderung des Erstellungsdatums. Sehr gut.

Bei Neuanlage: Verwirrung.
Da das Veröffentlichungsdatum zurzeit noch in der Zukunft liegt, falls nicht gleich geändert, erhält der Artikel bei Neuanlage 00:00 - was ja so richtig ist.
Erst bei Änderung des Veröffentlichungsdatum UND Änderung des Erstellungsdatums erhält der Artikel die richtige Zeit.
Es zeigt sich immer mehr, dass bei Neuanlage ein Artikel sofort veröffentlicht werden sollte und die richtige Uhrzeit erhält.

**Comment by cmb69** [comment]
> Bei Neuanlage: Verwirrung.
Da das Veröffentlichungsdatum zurzeit noch in der Zukunft liegt, falls nicht gleich geändert, erhält der Artikel bei Neuanlage 00:00 - was ja so richtig ist.
Erst bei Änderung des Veröffentlichungsdatum UND Änderung des Erstellungsdatums erhält der Artikel die richtige Zeit.

Das stimmt so nicht wirklich, und das Problem hat zunächst auch gar nichts mit Auto-Publishing zu tun. Es ist vielmehr so, dass bei der Neuanlage die aktuelle Uhrzeit gespeichert wird, und auch immer, wenn das Erstelldatum geändert wird. Allerdings wird die Uhrzeit vergessen, wenn man den Artikel ändert ohne das Datum zu ändern. Mein Fix ist also nicht korrekt.

**Comment by cmb69** [comment]
Das Problem sollte jetzt behoben sein. Bitte noch einmal testen.

**Comment by frase-git** [comment]
Schnelltest. Neuanlage.
Funktioniert.

**Comment by cmb69** [comment]
Super, danke!
