### ISSUE TITLE
"edit comments" button has empty href

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#49]
Wozu ist dieser Button da?
Oder kommt der von twocents?

**Comment by cmb69** [comment]
Der Button wird dem Admin angezeigt, falls ein kompatibles Kommentarplugin verfügbar ist (derzeit ist nur Twocents_XH kompatibel), und sollte zur Administration der Kommentare des jeweiligen Artikels führen.

Gibt's da irgendein Problem?

**Comment by frase-git** [comment]
Kein Problem.
Es könnte sein, dass bei mir etwas nicht in Ordnung ist.
Bei mir ist die einzige Stelle, um Kommentare zu bearbeiten, die betreffende Seite im Adminmodus anzuzeigen.
Auf dieser Seite sind auch die Kommentare mit den Bearbeitungsbuttons zu sehen.
Ein Klick auf "Kommentare bearbeiten" lädt die Seite nur neu (und ich bin oben, statt unten bei den Kommentaren).
Gibt es denn noch eine andere Stelle, wo man Kommentare bearbeiten kann?
Klar, wenn ein anderes Plugin verwendet wird, mit eigener Kommentarverwaltung, dann wäre dieser Button sinnvoll. Bei Twocents kann ich keinen Sinn erkennen. Eher einen Nachteil, durch das Laden der Seite. Das führt mich von den Kommentaren "weg" statt "hin".
Habe ich da was falsch verstanden, oder fehlt bei mir was?

**Comment by cmb69** [comment]
> Klar, wenn ein anderes Plugin verwendet wird, mit eigener Kommentarverwaltung, dann wäre dieser Button sinnvoll. Bei Twocents kann ich keinen Sinn erkennen. 

Ich bin ein Dösbaddel! Das habe [ich selbst auch schon festgestellt](https://github.com/cmb69/twocents_xh/blob/1.0alpha3/classes/RealblogBridge.php#L55), und obwohl das [ja okay ist](https://github.com/cmb69/realblog_xh/blob/3.0beta7/classes/CommentsBridge.php#L43), wird es  [nicht überprüft](https://github.com/cmb69/realblog_xh/blob/3.0beta7/views/article.php#L10-L12). Also wieder ein Bug! Wird sogleich behoben.

**Comment by frase-git** [comment]
Ging ja fix mit dem Fix.
Diesmal werde ich das nicht bei mir einarbeiten. Ich werde auf das nächste Update warten. Und das darf ruhig etwas dauern. Ist ja kein richtiger Bug.
Vielleicht wartest du überhaupt noch ein paar Tage mit weiteren Änderungen. Bei mir geht es nur langsam voran mit dem Testen. So viele Nebendinge ...
Es könnte sein , dass sich nur nach und nach andere Probleme ergeben. Die kommen dann kleckerweise.
Also Geduld.
Bisher: Macht 'nen guten Eindruck. Ein paar Wünsche tauchen auch auf. Die gibts dann aber am Ende für die übernächste Version (sofern ich es nicht vergesse).
Falls ein "echtes" Problem auftaucht, werde ich laut "brüllen".
;-)

**Comment by frase-git** [comment]
Habe den Fix nun doch mal eingearbeitet - Button ist weg.
Ich denke, es ist okay - oder?

**Comment by cmb69** [comment]
> Ich denke, es ist okay - oder?
Ich auch. :)
