### ISSUE TITLE
Improve pagination

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#51]
https://github.com/cmb69/realblog_xh/blob/master/classes/PaginationView.php#L59-L60
Die beiden • sind doch eher unglücklich.

Frag mich bitte nicht, was dort hin soll.
Es gibt nichts allgemeingültiges.
Vielleicht: "spans" um zwei Leerzeichen, die man dann per CSS stylen kann?
Oder um "X Artikel" und "Seite"?
Mir fällt nichts ein.

**Comment by cmb69** [comment]
> Die beiden • sind doch eher unglücklich.

Ja, hast recht – zumindest sollten sie nicht hart kodiert sein.

Insgesamt passt das aber sowieso nicht: "1 articles". Vielleicht ist es das beste, das komplett als Sprachstring zu gestalten; dann kann man bei Bedarf leicht spans hinzufügen, die Trennzeichen ändern, usw.

**Comment by frase-git** [comment]
Habe gerade local mehrere Seiten.
Habe die Seiten-Links sehr groß und mit Rahmen gemacht, damit man tippen kann.
So scheint mir der Text davor `X Artikel • Seite X von X •` ziemlich überflüssig.
Die Artikelanzahl ist auch nicht nötig - oder?
'n Haufen Tipparbeit gespart ;-)

**Comment by cmb69** [comment]
> So scheint mir der Text davor X Artikel • Seite X von X • ziemlich überflüssig.

Ich hatte das vom Forum abgeguckt – und siehe, die aktuelle Version zeigt "Seite X von Y" auch nicht mehr an. Das ist wirklich überflüssig. Die Anzahl der Artikel anzuzeigen, finde ich aber ganz nützlich – schließlich weiß man nicht gleich, wieviele Artikel auf einer Seite gelistet werden.

Bezüglich des Stylings der Seitenlinks: da hatte ich überlegt, die zu `.realblog_button`s zu machen – sinnvoll?

**Comment by frase-git** [comment]
wie es ist reicht.
es gibt p.realblog_pagination, den href und span
kann man alles einzeln stylen

**Comment by cmb69** [comment]
> wie es ist reicht.
es gibt p.realblog_pagination, den href und span
kann man alles einzeln stylen

Mir ging es um das Default-Styling, bzw. letztlich um die Daseinsberechtigung von `.realblog_button` an sich. Eigentlich braucht man diese Klasse nicht (und sie ist ja auch etwas verwirrend benannnt; schließlich handelt es sich um Links), aber wenn sie schon verwendet wird, dann vielleicht auch an anderen Stellen?

**Comment by frase-git** [comment]
Der Grundgedanke ist richtig. Eine Realblog-Button-Klasse, die überall gleich ist.
Aber zurzeit ist das ja auch nicht konsequent.
Default-Styling: Dann mach' es doch mit Rahmen und etwas padding um die Seiten-Links.
Ändern kann es jeder, wie er will.

**Comment by cmb69** [comment]
> Der Grundgedanke ist richtig. Eine Realblog-Button-Klasse, die überall gleich ist.
Aber zurzeit ist das ja auch nicht konsequent.

Dann sollte **das** geändert werden, finde ich: entweder weg mit `.realblog_button`, oder es kosequent einsetzen (abgesehen von den Paginierungslinks auf jeden Fall noch für die "Read more" Links). Und ja, `.realblog_button` ist schlecht gestaltet (zumindest sollte keine `color` angegeben werden, wenn der `background` unbekannt ist). Außerdem sehe ich keinen wirklichen Sinn darin, einem `span` um das `a` die CSS-Klasse zuzuweisen (okay, vielleicht bezüglich des Boxmodells, aber da kann man [heutzutage](http://caniuse.com/#feat=css3-boxsizing) bei Bedarf ja auch problemlos `box-sizing` verwenden).

Derzeit tendiere ich dazu, `.realblog_button` zu erhalten, aber minimalistischer zu stylen, und einen umfangreicheren Regelsatz als Kommentar ins Stylesheet zu setzen.

**Comment by cmb69** [comment]
Die .realblog_button Sache habe ich mal als #56 ausgelagert.

**Comment by cmb69** [comment]
Ich habe jetzt das überflüssige "Seite von Seiten" entfernt, sowie die • Trennzeichen. Statt dessen habe ich CSS-Klassen eingeführt, mit der das ganze vernünftig gestaltbar sein sollte. Und ich habe PaginationView in Pagination und eine [pagination View](https://github.com/cmb69/realblog_xh/commit/bdb02065b39c2e6dd2ffed76d67326fb0ef61d08#diff-863b4291a3d495985c472e6c8f7d288a) gesplittet; das sollte flexibel genug sein.

So langsam wird's. Danke! :)
