### ISSUE TITLE
Improve pagination of archive overview

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#53]
kleines Problem:
◀ und ▶ sind auch nicht schön.
Vielleicht Option: Zeichen zum Blättern?
Oder ganz anders:
Jahresarchiv: 2012 2013 2014 … 2017
also ähnlich wie Pagination
fände ich besser - ist leichter anzutippen

größeres Problem:
Jahresarchiv
```
hx (Monat)
ul
    li
        hx (Monat)
        ul
            li
        /ul
    /li
/ul
```
erkennbar?

**Comment by cmb69** [comment]
Die fehlerhafte Listenstruktur habe ich nach #55 "verschoben". Zur Paginierung äußere ich mich später noch.

**Comment by cmb69** [comment]
> Oder ganz anders:
Jahresarchiv: 2012 2013 2014 … 2017
also ähnlich wie Pagination
fände ich besser - ist leichter anzutippen

Das erscheint mir auch am sinnvollsten, zumal es dann analog zur Blog-Paginierung funktioniert. Ich arbeite mal einen Pull-Request aus.

**Comment by cmb69** [comment]
> Jahresarchiv: 2012 2013 2014 … 2017

Siehe auch #22.

**Comment by frase-git** [comment]
> Jahresarchiv: 2012 2013 2014 … 2017

In dieser Jahresliste sollten Jahre ohne Einträge gar nicht erscheinen ... ???

**Comment by cmb69** [comment]
> In dieser Jahresliste sollten Jahre ohne Einträge gar nicht erscheinen ... ???

ACK! Ansonsten gibt es schnell ein ähnliches Problem wie bei cmb69/ocal_xh#17.

**Comment by cmb69** [comment]
Sorry, muss ich auf 3.0rc1 verschieben.
