### ISSUE TITLE
show: category name

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#54]
Welche Variable steht zur Verfügung um den Kategorienamen anzeigen zu lassen?
z.B. auf der Testseite im Artikelheader (schwarz) nach dem Datum?
Im Teaser und im Artikel?

**Comment by cmb69** [comment]
In den Views referenziert `$article` die verfügbare Artikel-Information. Im Artikel kann per `$article->categories` auf die Katergorien zugegriffen werden; in der Übersicht dürfte `$article->categories` nicht gesetzt sein; da könnte ich bei Bedarf nachbessern. Aber: die Kategorien werden in ->categories als `,foo,bar,baz` dargestellt (so sind sie halt derzeit gespeichert). Das müsste für die Darstellung aufbereitet werden:
````
$categories = explode(',', trim($article->categories));
````

**Comment by frase-git** [comment]
Versucht in article.php hinter die Datumsausgabe:
`<?php echo $this->$categories = explode(',', trim($article->categories));?>`
Da erscheint nur "Array". Das konnte nicht gutgehen ;-)

Also Wunsch: Kategoriename (nach dem Artikel-Datum) ausgeben.

**Comment by cmb69** [comment]
> Also Wunsch: Kategoriename (nach dem Artikel-Datum) ausgeben.

Denk dran: es gibt potentiell mehrere Kategorien. Du kannst ja mal folgendes probieren:
````
<?=$this->escape(trim($this->article->categories, ','))?>
````
Eine allgemeine Lösung ist etwas aufwendiger, da man zumindest den Fall, dass keine Kategorie zugeordnet ist, besonders behandeln müsste ("keine Kategorie" oder Anzeige ganz unterdrücken).

**Comment by frase-git** [comment]
Das funktioniert!
Danke!
Zumindest bei den Artikeln. Wie du schon erwähntest, bei den Teasern nicht.
Was passiert, wenn keine Kategorie zugeordnet ist habe ich noch nicht getestet.
Idee:
Wenn einem Artikel keine Kategorie zugeordnet wurde, erhält er automatisch als default "all" oder "other".
Der default-Name müsste sprachabhängig wählbar sein. Könnte auch gleich im Kategorie-Input-Feld als default drin stehen.

**Comment by cmb69** [comment]
> Wenn einem Artikel keine Kategorie zugeordnet wurde, erhält er automatisch als default "all" oder "other".

Macht IMHO wenig Sinn, es sei denn man würde genau 1 Katergorie zulassen.

Und ja, es ist wohl sinnvoll allgemein die Kategorien anzuzeigen (eventuell Konfig-Option), aber dann halt vernünftig stylebar. Tags könnten ganz nett aussehen. Vielleicht auch per Sprachzeichenkette ("abgelegt unter …") Und eigentlich sollten die einzelnen Kategorien auch verlinkt werden, so dass man alle Artikel einer Kategorie anzeigen lassen kann (nicht nur, wenn das vom Webmaster per Pluginaufruf vorbereitet wurde). Da wäre aber #21 Voraussetzung. Und dann müsste man sich bezüglich der Suche noch was einfallen lassen (auf einer Kategorie-Übersichtsseite nur in der jeweiligen Kategorie suchen, zum Beispiel). Mir scheint, der Realblog hat noch einen langen Weg bis er seinem Namen gerecht wird.

**Comment by frase-git** [comment]
> Mir scheint, der Realblog hat noch einen langen Weg bis er seinem Namen gerecht wird.

;-)))
Vielleicht war das der Grund, warum Svasti keine Zeit mehr hat.
Das eben Besprochene sehe ich als Option für die sehr ferne Zukunft.
Ich muss bei meinen Ideen besser kenntlich machen, was wichtig und was Traum ist.
Also: Das hier auf die Future-List.

**Comment by cmb69** [comment]
> Also: Das hier auf die Future-List.

Da bin ich mir gar nicht mal so sicher. Zumindest eine Liste der Kategorien (ähnlich wie Realblog_link()) ist schon sehr wünschenswert. Und wenn erst mal ein RC raus ist, dann wird es wohl recht lange dauern, bis ich wieder neue Features hinzufügen werde (gibt ja noch mehr Plugins). Mal schauen.

**Comment by cmb69** [comment]
Das ist eigentlich ein Duplikat von #62.
