### ISSUE TITLE
Archive view never closes <ul>s

### ISSUE THREAD

**Issue by cmb69** [cmb69/realblog_xh#55]
The archive view never emits `</ul>` and so produces invalid HTML.

**Comment by frase-git** [comment]
Noch etwas zur Archiv-Ansicht:
Die Monats-Überschriften haben (die von mir festgelegte) `<h2>`.
Theoretisch völlig richtig.
Nun gefällt mir zwar, dass sie 2. Ordnung sind, aber sie sind (aus styles.css) für mein Auge zu groß (hier im Archiv).
Vorschlag:
Das gesamte Archiv in einen `div` oder `section` mit Klasse (.archiveView) packen, damit ich die Überschriften (und andere Elemente) explizit ansprechen kann?

**Comment by cmb69** [comment]
> Kannst du das verschieben?

Nicht wirklich. Ich kann nur löschen, und woanders neu posten – aber dann stimmt der Name nicht. Im Zweifel kannst Du den Kommentar aber auch einfach von woanders verlinken (den Link findest Du hinter "commented" bei der Zeitangabe).

> Das gesamte Archiv in einen div oder section mit Klasse (.archiveView) packen, damit ich die Überschriften (und andere Elemente) explizit ansprechen kann?

section will ich noch nicht verwenden, aber einschließen in ein div ist sinnvoll (auch als Vorarbeit für die HTML5 Struktur), vermutlich für alle Views.

**Comment by cmb69** [comment]
> section will ich noch nicht verwenden, aber einschließen in ein div ist sinnvoll (auch als Vorarbeit für die HTML5 Struktur), vermutlich für alle Views.

Siehe #57.
