### ISSUE TITLE
description may be truncated in the middle of a word

### ISSUE THREAD

**Issue by cmb69** [cmb69/realblog_xh#58]
When an article is viewed, its teaser is used as `<meta name="description">`. As the description is supposed to be not longer than 150 characters (at least Google appears to want this), the teaser is truncated. However, the truncation doesn't take into account word boundaries so a word may be truncated in the middle. That doesn't look nice, and may result in confusing and even wrong information.

**Comment by frase-git** [comment]
Das wusste ich bisher noch gar nicht.
Nicht in jedem Artikel steht gleich am Anfang relevanter Inhalt.
Somit ist diese Funktion zumindest fraglich - wenn es mich auch freut, dass ich sie eben entdeckt habe.

Wäre es nicht besser, die Überschrift zu nehmen?
(Da hat es sicher schon ausreichend Diskussion gegeben)
Das ist kein Wunsch - nur 'ne Frage.

**Comment by cmb69** [comment]
> Nicht in jedem Artikel steht gleich am Anfang relevanter Inhalt.

Ja, ich weiß, aber besser eine nicht ganz so relevante Description als die allgemeine Description (die ist schließlich noch weniger relevant für die Artikel-Seite). Außerdem kann man den Teaser ja entsprechend gestalten, und letztlich ist die Description auch nur ein *Hinweis* für Suchmaschinen.

> Wäre es nicht besser, die Überschrift zu nehmen?

Die steht schon im `<title>`, welcher ohnehin (nicht nur, aber v.a. auch für SEO) wichtiger ist.

**Comment by frase-git** [comment]
Alles klar
Gut!
