### ISSUE TITLE
Extend article meta info

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#62]
Die Überschrift ist etwas übertrieben: bitte prüfen und bei Relevanz als "Wunsch" einordnen ;-)
1.
`.realblog_show_date` und evtl. später Kategoriename, Autor ... usw. in einen eigenen DIV setzen - evtl. `.article_entry_preview_header` und `.realblog_article_header` oder vielleicht etwas passenderes.
2.
Den neuen DIV **über** die Artikel-Überschrift setzen.

Begründung:
In beiden Ansichten (Artikel und Preview) gibt es darüber z.B. die Seitenüberschrift und/oder die Suche.
Der neue DIV könte als optische Abgrenzung zum oberen allgemeinen Teil gestyled werden.
Das Datum zwischen Überschrift und Text (wie bisher) scheint mir ungünstig - lieber darüber.
Artikelüberschrift und Fließtext bzw. Vorspann kommen näher zusammen.
Der neue DIV könnte zukünftige Artikelangaben (Autor ...) aufnehmen.

**Comment by frase-git** [comment]
Ich habe jetzt auf der Testseite - zur Demonstration, wie ich es mir wünsche - die article.php und articles.php geändert.
Das ist natürlich nicht updatefähig und deshalb suboptimal ;-)
In der Artikel-Ansicht habe ich auch die Kategorien in den header eingefügt.
`trim` bringt hier natürlich keine guten Ergebnisse. (siehe Artikel "Webfont ...")

**Comment by cmb69** [comment]
> Ich habe jetzt auf der Testseite - zur Demonstration, wie ich es mir wünsche - die article.php und articles.php geändert.

Danke! Sieht übrigens sehr gut aus. Bzgl. des `<div>` bin ich ganz bei Dir (.realblog_show_date sollte dann wohl zum `<span>` werden). Allerdings bzgl. der Vertauschung der Reihenfolge nicht wirklich. Zum Beispiel wird es auf https://de.wordpress.org/news/ auch so gemacht wie beim Realblog – allerdings sinnvoller gestylt: das Datum sollte nicht bold, sonder eher dezenter als normal sein.

Vergleiche auch ein [W3C Beispiel](http://w3c.github.io/html/sections.html#example-f99f39f2) für einen Blog-Post mit [einem auf selfHTML](https://blog.selfhtml.org/2013/04/29/html5-serie-inhalte-strukturieren/).

Aber kann man nicht auch anstatt die Views anzupassen die Reihenfolge per CSS vertauschen. Ich bin da ja kein Spezi, aber `position:relative; top:…` (Überschrift ein wenig runter, Datum ordentlich hoch) kann u.U. schon genügen. Genereller geht es wohl [so](http://stackoverflow.com/questions/17455811/swap-div-position-with-css-only).

Sollte das nicht passen, dann ist natürlich auch eine Konfigurationsoption denkbar.

**Comment by frase-git** [comment]
> Sollte das nicht passen, dann ist natürlich auch eine Konfigurationsoption denkbar.

Na ja, hast du Lust darauf? So viele Optionen programmieren ... ?
Wir könnten jetzt ellenlang diskutieren.
Die Version von selfHTML gefällt mir bestens - auch die Artikelübersicht.
Vertauschen per CSS scheint mir sehr komliziert. Habe ich noch nicht gemacht.
Falls dir mein Wunsch gefällt - mach es.
Das dürfte für bisherige User von Realblog wenig Probleme bereiten. Neu stylen (an einigen Punkten) müssen sie sowieso.

**Comment by cmb69** [comment]
> Na ja, hast du Lust darauf? So viele Optionen programmieren ... ?

Programmieren ist kein Problem – das Testen allerdings auf Dauer schon. Idealerweise also möglichst wenig Optionen, aber das ist halt nicht immer machbar.

> Vertauschen per CSS scheint mir sehr komliziert. Habe ich noch nicht gemacht.

Ich auch nicht; den Thread hatte ich schnell ergoogelt.

> Falls dir mein Wunsch gefällt - mach es.

Mir persönlich nicht so, aber vielleicht finden das andere auch besser?

**Comment by frase-git** [comment]
Auf die Spitze getrieben: Habe die Kommentar-Anzahl auch noch in den Header gepackt.
So gesehen könnten alle Zusatzinfos wie Datum, Kommentare Autor ... in diesen Header.
Dann Konfig-Option: **über** oder **unter** der Überschrift ?

**Comment by cmb69** [comment]
> So gesehen könnten alle Zusatzinfos wie Datum, Kommentare Autor ... in diesen Header.

Ja, abgesehen vom Autor (zunächst ist das ja immer "derselbe").

> Dann Konfig-Option: über oder unter der Überschrift ?

Okay, ich arbeite mal was aus.

**Comment by cmb69** [comment]
@frase-git Schau Dir bitte mal #70 an. Ich habe die Konfigurationsoption noch nicht eingebaut; will erst mal sehen, ob die neue Meta-Info so passt.

**Comment by frase-git** [comment]
Jetzt zeigt sich wieder mal, dass ich Github immer noch nicht verstanden habe.
Muss ich nun die Dateien händich aktualisieren, oder gibt es die Änderungen als Paket zum Runterladen?
Oder sollte ich "nur schauen"?

**Comment by frase-git** [comment]
![screen-realblog-meta](https://cloud.githubusercontent.com/assets/24246330/23103994/5f2b6b42-f6c5-11e6-8d1d-94290a71af3e.png)


Sieht hier natürlich schlimm aus. Ist aber alles schön per CSS lösbar. Und wir sprechen in ganzen Sätzen!
Jetzt noch oben/unten - dann scheint das zu passen.

**Comment by cmb69** [comment]
> Stopp! Habe den Branch gefunden.

Ah, gut!

> Jetzt noch oben/unten - dann scheint das zu passen.

Okay, mach ich gleich.

Und da Du gerade sehr aktiv testest (danke!), pass auf #71 auf – ab commit 28a49b2a müssen bestehende Kommentardateien umbenannt werden (`comments123.csv` → `realblog123.csv`), wenn die Kommentare weiter verwendet werden sollen.

**Comment by frase-git** [comment]
> pass auf #71 auf ...

Gehe ich richtig in der Annahme, dass ich warte, bis du das Besprochene mergest und ich dann den offiziellen Branch für mich anpasse?

**Comment by cmb69** [comment]
> Gehe ich richtig in der Annahme, dass ich warte, bis du das Besprochene mergest und ich dann den offiziellen Branch für mich anpasse?

Ja, das wird das beste sein. :)

**Comment by cmb69** [comment]
@frase-git Erledigt. :)

**Comment by cmb69** [comment]
Ich habe gerade gemerkt, dass die Anzeige bei Artikeln ohne Kategorie keinen Sinn macht. Schnell gefixt mit commit 94b5013a.
