### ISSUE TITLE
realblog_pagination active page

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#63]
Die aktive Seite hat jetzt einen Link.
Somit kann man in der Pagination nicht mehr die aktive Seite erkennen.
`<span class=".realblog_pagination_inactive">`  statt `<a>` wäre wohl angemessen?

(Die Rede ist vom aktuellen branch)

**Comment by cmb69** [comment]
Danke für die Meldung. 

Ich hatte als Klasse bereits [`.realblog_pag_current` vorgesehen](https://github.com/cmb69/realblog_xh/commit/bdb02065b39c2e6dd2ffed76d67326fb0ef61d08#diff-863b4291a3d495985c472e6c8f7d288aR8) und würde es dabei belassen. Natürlich sollte der If-Zweig auch ausgeführt werden.

**Comment by frase-git** [comment]
>  `.realblog_pag_current`

Besser.
