### ISSUE TITLE
realblog_table  show categories

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#65]
Wunsch:
In der Artikelübersicht unter Artikel bearbeiten könnten die zugeorneten Kategorien angezeigt werden.
Das habe ich jetzt in der Testpraxis vermisst.
Es könnte eine neue Spalte hinzugefügt werden. Dazu müsste evtl. `.realblog_table` die Regel `table-layout: fixed;` erhalten. Da gleichen sich die Spalten an.
Oder, falls das ungünstig ist:
`<td class="realblog_table_title" colspan="8">XXX</td>`
den colspan aufteilen in z.B. 5 & 3 und in die letzte `td` die Kategorie(n).
???

**Comment by cmb69** [comment]
> In der Artikelübersicht unter Artikel bearbeiten könnten die zugeorneten Kategorien angezeigt werden.

Ja, sehr sinnvoll! Das leicht verwandte issue #21 steht ja auch schon auf der ToDo-Liste.

Bezüglich der Realisierung (Layout) bin ich mir nicht sicher. Die ganze Tabelle ist sowieso fraglich (die letzten drei Spalten bräuchten eigentlich gar nicht so viel Platz, und mit den colspans wird zuviel getrickts). Wie wäre es fürs erste, wenn die jeweils zweite Zeile tatsächlich nur 1 Spalte enthält, und die Katergorien rechts floaten?

**Comment by frase-git** [comment]
> die letzten drei Spalten bräuchten eigentlich gar nicht so viel Platz

für die Überschriften Icons finden und `table-layout: fixed;` ;-)
dann wäre Platz

aber: mach das Layout, wie es dir gefällt oder es einfacher ist
bisher ist sie schön übersichtlich

**Comment by cmb69** [comment]
> aber: mach das Layout, wie es dir gefällt oder es einfacher ist

Ich hab's fürs erste tatsächlich mit colspan gelöst – das sollte aber insgesamt noch mal überarbeitet werden. Diese Tabelle ist eine mittlere Katastrophe (hinter den Kulissen).
