### ISSUE TITLE
number of comments wrong

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#66]
Ausgeblendete Kommentare werden in der Artikelübersicht trotzdem im Zähler berücksichtigt.

(Bin mir nicht sicher, ob ich das schonmal hier, oder bei miniblog festgestellt habe.)

**Comment by frase-git** [comment]
Ha, es war bei miniblog.
https://cmsimpleforum.com/viewtopic.php?f=16&t=7889&p=54130&#p54130

**Comment by cmb69** [comment]
Hm, das sieht mir eher nach einem Problem bei Twocents_XH aus. Muss ich aber noch prüfen.

**Comment by cmb69** [comment]
Ja, ist tatsächlich ein Twocents_XH Problem, siehe cmb69/twocents_xh#19. Da wird's auch mal dringend Zeit für ein Update.
