### ISSUE TITLE
link() and Popular() should use proper headings

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#67]
Ich verwende realbloglink in der Sidebar für realblog_most_popular und realblog_latest.
(ich nenne hier nur die Klassen - einfacher)

Normal sähe das Ergebnis so aus:
`<p class="realbloglink">Die beliebtesten Artikel</p>`

Nun benötige ich aber aus Strukturgründen an dieser Stelle eine `<h1>`.
Also schreibe ich in die Spracheinstellungen
`<h1>Die beliebtesten Artikel</h1>`

Im Firefox kommt dabei heraus:
```
<p class="realbloglink"></p>
<h1>Die beliebtesten Artikel</h1>
<p></p>
```
Ich habe also zwei überflüssige wirklich störende `<p>`.
Vielleicht könnte man schreiben in most-popular.php:
statt:
`<p class="realbloglink"><?=$this->text('most_popular')?></p>`
eben:
`<span class="realbloglink"><?=$this->text('most_popular')?></span>`
Das gleiche ntürlich für realblog_latest.
Damit es keine Probleme gibt, könnte man im Style hinzufügen `display: block;`
```
span.realbloglink {
    display: block;
}
```
Watmeinste?

**Comment by cmb69** [comment]
> Watmeinste?

Wenn ich mir die Message von commit f0ab5ece anschaue, dann würde ich sagen, da sollte statt dem `<p>` eigentlich gleich ein passendes `<h?>` ausgegeben werden. Könnte dafür nicht [Heading→Level](https://github.com/cmb69/realblog_xh/blob/master/config/config.php#L9) verwendet werden?

**Comment by frase-git** [comment]
Wenn das überall allgemein passen täte?
Gut.

Für mich kann ich es z.B. so lösen:
```
.realblog_most_popular p:nth-child(-n+3) {
...
}
```
Dann sind die zwei ersten angetroffenen `<p>` eliminierbar.

**Comment by cmb69** [comment]
> Wenn das überall allgemein passen täte?

Tja, da bin ich mir auch nicht sicher, aber einen Versuch ist's wert, denke ich. Kann zur Not immer noch geändert werden, bis zur 3.0.
