### ISSUE TITLE
console warning

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#68]
Eine kleine Warnung in der FF-Console bei Artikelansicht:

> ReferenceError:
 assignment to undeclared variable TWOCENTS

Debugger sagt:
`<script type="text/javascript">/* <[CDATA[ */TWOCENTS = {"comments_markup":"HTML","label_new":"schreibe einen Kommentar","message_delete":"Dieser Kommentar wird gel\u00f6scht."};/* ]]> */</script>`

**Comment by cmb69** [comment]
Hm, das ist ein Ding! Die gepostete Zeile sollte maximal eine Warnung triggern, aber eigentlich (jedenfalls nach meinem bisherigen Verständniss), dürfte beim Löschen eines Posts kein Text in der Confirm-Message erscheinen (eben wegen des ReferenceError). Das klappt aber bei mir in Firefox und Chrome, und keiner von beiden meldet mir den Fehler.

Auf jeden Fall werde ich den [Fehler in Twocents_XH](https://github.com/cmb69/twocents_xh/issues/27) beheben.

**Comment by cmb69** [comment]
> Die gepostete Zeile sollte maximal eine Warnung triggern, aber eigentlich (jedenfalls nach meinem bisherigen Verständniss), dürfte beim Löschen eines Posts kein Text in der Confirm-Message erscheinen (eben wegen des ReferenceError).

Da war mein bisheriges Verständnis nicht ganz richtig, denn auch beim Löschen eines Posts dürfte maximal eine Warnung kommen. Den ReferenceError kann ich mir aber nicht erklären, da das `<script>` Element nicht im strict mode ausgeführt werden sollte. Ist aber nicht so wichtig – gefixt wird's auf jeden Fall.
