### ISSUE TITLE
Comments count wrong in article view

### ISSUE THREAD

**Issue by frase-git** [cmb69/realblog_xh#72]
Der Kommentar-Zähler ist in der Artikel-Ansicht falsch.

(morgen abend wieder ...)

**Comment by cmb69** [comment]
> Der Kommentar-Zähler ist in der Artikel-Ansicht falsch.

Stimmt. Da habe ich beim Mergen Mist gebaut.

**Comment by cmb69** [comment]
Nö, hatte nichts mit dem Mergen zu tun – hatte ich einfach übersehen. Danke für den Report!
